#!/bin/bash
# DAG-38: evidence/dual_gpu/check.sh
#
# Daily evidence check for the Desktop NVIDIA dual-GPU lane.
# Records nvidia-smi summary + PCIe topology + GPU memory pressure
# to evidence/dual_gpu/heartbeat.json. CWD-invariant.
#
# Schedule: daily 04:30 UTC (10 min after the SOTA snapshot cron).
# Wired by install_launchd.sh as
# com.phenotype.pheno-harness.dual-gpu-check.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EVIDENCE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)/evidence/dual_gpu"
HEARTBEAT="$EVIDENCE_DIR/heartbeat.json"
MANIFEST="$EVIDENCE_DIR/host_manifest.yaml"

mkdir -p "$EVIDENCE_DIR"

now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
host="$(hostname)"
nvidia_out="$(nvidia-smi --query-gpu=index,name,memory.used,memory.total,utilization.gpu,temperature.gpu --format=csv,noheader 2>/dev/null || echo "")"
pcie_out="$(nvidia-smi --query-gpu=pcie.link.gen.current,pcie.link.width.current --format=csv,noheader 2>/dev/null || echo "")"

# Build a stable JSON envelope.
cat > "$HEARTBEAT.tmp" <<JSON
{
  "captured_at": "$now",
  "host": "$host",
  "nvidia_smi": $(printf '%s' "$nvidia_out" | python3 -c '
import json, sys
rows = [r for r in sys.stdin.read().splitlines() if r.strip()]
out = []
for r in rows:
    parts = [p.strip() for p in r.split(",")]
    if len(parts) >= 6:
        out.append({
            "index": int(parts[0]),
            "name": parts[1],
            "memory_used_mb": int(parts[2]),
            "memory_total_mb": int(parts[3]),
            "utilization_pct": int(parts[4]),
            "temperature_c": int(parts[5]),
        })
print(json.dumps(out))
' 2>/dev/null || echo '[]'),
  "pcie": $(printf '%s' "$pcie_out" | python3 -c '
import json, sys
rows = [r for r in sys.stdin.read().splitlines() if r.strip()]
out = []
for r in rows:
    parts = [p.strip() for p in r.split(",")]
    if len(parts) >= 2:
        out.append({"gen": parts[0], "width": parts[1]})
print(json.dumps(out))
' 2>/dev/null || echo '[]'),
  "evidence_label": "live_verified"
}
JSON

mv "$HEARTBEAT.tmp" "$HEARTBEAT"

# Update host_manifest.yaml (rolling 7-day tail).
if [ ! -f "$MANIFEST" ]; then
  cat > "$MANIFEST" <<YAML
# Auto-generated by evidence/dual_gpu/check.sh — do not hand-edit.
captures:
YAML
fi
echo "  - captured_at: $now" >> "$MANIFEST"
echo "    host: $host" >> "$MANIFEST"
echo "    gpus: $(echo "$nvidia_out" | wc -l | tr -d ' ')" >> "$MANIFEST"

echo "evidence/dual_gpu heartbeat updated: $now"
