[package]
name = "pheno-cache-adapter"
version = "0.2.0"
edition = "2021"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
dashmap = "5"
tokio = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
