"""Rendering for INVENTORY.md and FILES.md.

Table rendering is deliberately dumb and stable: fixed column order, explicit
tiebreakers, no timestamps. Re-running on the same commit yields byte-identical
output, which is what makes `generate.py --check` meaningful in CI.
"""

from __future__ import annotations

import os
from collections import Counter

from .definitions import CODE_EXT, DOC_EXT, LIMIT_HARD, LIMIT_TARGET

GENERATED_BY = "Generated by `scripts/atlas/generate.py`. Do not edit by hand."


def esc(value) -> str:
    return str(value).replace("|", "\\|")


def table(headers, rows) -> str:
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join("---" for _ in headers) + "|"]
    lines.extend("| " + " | ".join(esc(cell) for cell in row) + " |" for row in rows)
    return "\n".join(lines)


def ext_of(path: str) -> str:
    return os.path.splitext(path)[1].lstrip(".").lower()


def top_dir(path: str) -> str:
    return path.split("/", 1)[0] if "/" in path else "(root)"


def header(title: str, revision: str, extra: list[str] | None = None) -> list[str]:
    lines = [f"# {title}", "", GENERATED_BY, ""]
    if extra:
        lines.extend(extra)
    lines.extend([
        f"- Source revision: `{revision}` (`git rev-parse HEAD`)",
        "- Source of truth: `git ls-files` — tracked files only, so build output "
        "and untracked files are excluded.",
        "",
    ])
    return lines


def render_inventory(revision: str, rows, unowned, totals, packages) -> str:
    out = header("PhenoShared codebase inventory", revision, extra=[
        "One row per tracked `Cargo.toml` directory: what it is, how big it is, "
        "how it is tested, and when it last moved.",
        "",
        "## Definitions",
        "",
        "- **LOC** = logical line count = number of `\\n` bytes, plus 1 when a "
        "non-empty file does not end in a newline. `wc -l` reports one less for "
        "those files; the stricter definition is used so the 350/500 gate cannot "
        "undercount.",
        "- **Ownership** = a file belongs to the deepest tracked `Cargo.toml` "
        "directory containing it. Nested packages are therefore not double "
        "counted, and a wrapper crate is not credited with its children's code. "
        "The `LOC`/`files`/`tests` columns are tree totals, not own totals.",
        "- **tests** = test declarations, language by language: Rust `#[test]` / "
        "`#[<crate>::test]` attributes, Python `def test_`, Go `func Test`, "
        "JS/TS `it(` / `test(` at line start. This counts declarations, not a "
        "verified passing suite.",
        "- **kind** = workspace membership: `member` (listed in the root "
        "`[workspace] members`), `excluded`, `sub-workspace` (declares its own "
        "`[workspace]`), `non-member` (has `[package]`, not a member), "
        "`manifest-only`, `workspace-root`. Flavour is `lib` / `bin` / `lib+bin` "
        "/ `meta` from the `[lib]` and `[[bin]]` tables.",
        "- **docs** = tracked `.md`/`.mdx` files inside the package tree.",
        "- **os_cfg** = distinct `target_os = \"...\"` values appearing in the "
        "package (`-` when the package is platform-independent).",
        "- **last** = newest author date (`%aI`) across the package's files.",
        "- **role** = `[package] description`; else the first prose line of the "
        "package `README.md`; else inferred from the package name. Inferred "
        "roles are prefixed `~`.",
        "",
        "## Totals",
        "",
        table(["metric", "value"], [
            ["Cargo package directories (tracked `Cargo.toml`)", totals["packages"]],
            ["root workspace members", totals["members"]],
            ["tracked files", totals["files"]],
            ["tracked LOC (all file types)", totals["loc"]],
            ["Rust files", totals["rs_files"]],
            ["Rust LOC", totals["rust_loc"]],
            ["test declarations (all languages)", totals["tests"]],
            ["Rust LOC inside root workspace members", totals["member_loc"]],
            ["files outside every nested package (the `workspace-root` bucket)",
             f"{unowned['files']} files / {unowned['loc']} LOC"],
        ]),
        "",
        f"{totals['members']} of {totals['packages']} package directories belong to "
        "the single root Cargo workspace. The rest are tracked crates outside it: "
        "absorbed vendor trees, test fixtures, nested fuzz/Tauri workspaces, and "
        "template scaffolds.",
        "",
        f"## Packages ({totals['packages']})",
        "",
        "Sorted by tree LOC descending.",
        "",
        table(
            ["path", "package", "kind", "LOC", "rs files", "files", "tests",
             "docs", "os_cfg", "last", "role"],
            [[r["dir"], r["name"], r["kind"], r["loc"], r["rs"], r["files"],
              r["tests"], r["docs"], r["os"], r["last"], r["role"]] for r in rows],
        ),
        "",
        f"Files not inside any nested package directory belong to the "
        f"`workspace-root` row above: {unowned['files']} files, "
        f"{unowned['loc']} LOC, {unowned['tests']} test declarations. They are "
        "repository-level sources and docs, not unowned orphans.",
        "",
    ])
    return "\n".join(out)


def render_files(revision: str, files: dict, h: dict) -> str:
    paths = sorted(files)
    code = sorted((p for p in paths if ext_of(p) in CODE_EXT),
                  key=lambda p: (-files[p]["loc"], p))
    docs_big = sorted((p for p in paths
                       if ext_of(p) in DOC_EXT and files[p]["loc"] > 200),
                      key=lambda p: (-files[p]["loc"], p))
    by_ext = Counter(ext_of(p) or "(none)" for p in paths)
    by_dir = Counter(top_dir(p) for p in paths)
    dir_loc = Counter()
    for path in paths:
        dir_loc[top_dir(path)] += files[path]["loc"]
    out = header("PhenoShared per-file inventory", revision, extra=[
        "- **LOC** = `\\n` bytes + 1 when a non-empty file lacks a trailing newline.",
        "- **tests** = test declarations in that file (see `INVENTORY.md`).",
        "- **entry** = entrypoint: `main.rs` / `src/bin/**` / `fn main(` / "
        "`func main(` / `main.py` / `__main__.py` / executable file with a shebang.",
        "- **code file** = extension in the source allowlist (Rust, Python, Go, "
        "JS/TS, C/C++, shell, and other source languages).",
        "- **source file** = a regular, non-binary file whose extension is in the "
        "source allowlist. The repository's 350/500-line rule targets source "
        "modules, so the gate sections below are led by the source-only list; "
        "the all-files lists follow for completeness.",
        "- The complete per-file row list is: all code files, all docs over 200 "
        "lines, and — in the gate sections below — every tracked file over the "
        "limit regardless of type. Remaining non-code files are covered by the "
        "summaries.",
        "",
        f"## Summary: {len(paths)} tracked files, "
        f"{sum(files[p]['loc'] for p in paths)} LOC",
        "",
        table(["top-level area", "files", "LOC"],
              [[d, n, dir_loc[d]] for d, n in sorted(by_dir.items(),
                                                     key=lambda x: (-x[1], x[0]))]),
        "",
        "## Summary by extension (top 40)",
        "",
        table(["extension", "files"],
              [[(e if e != "(none)" else "(no extension)"), n]
               for e, n in sorted(by_ext.items(), key=lambda x: (-x[1], x[0]))[:40]]),
        "",
        f"## Code files ({len(code)})",
        "",
        "Sorted by LOC descending.",
        "",
        table(["path", "LOC", "tests", "entry"],
              [[p, files[p]["loc"], files[p]["tests"],
                "yes" if files[p]["main"] else ""] for p in code]),
        "",
        f"## Docs over 200 lines ({len(docs_big)})",
        "",
        "Documentation length watchlist. The repo's size rule names source files, "
        "but these are the docs most likely to be hiding unfactored material.",
        "",
        table(["path", "LOC"], [[p, files[p]["loc"]] for p in docs_big]),
        "",
        f"## GATE VIOLATION — source files over {LIMIT_HARD} lines: "
        f"{len(h['src_hard'])}",
        "",
        "The repository's rule targets source modules, so this is the list that "
        "counts. Repo rule: modules at or below 500 lines hard.",
        "",
        table(["path", "LOC", "over by", "tests", "area"],
              [[p, n, n - LIMIT_HARD, files[p]["tests"], top_dir(p)]
               for p, n in h["src_hard"]]),
        "",
        f"## GATE VIOLATION — source files over {LIMIT_TARGET} lines: "
        f"{len(h['src_target'])}",
        "",
        "Repo rule: target 350 lines. Includes every file in the section above.",
        "",
        table(["path", "LOC", "over by", "tests", "area"],
              [[p, n, n - LIMIT_TARGET, files[p]["tests"], top_dir(p)]
               for p, n in h["src_target"]]),
        "",
        f"## All tracked files over {LIMIT_HARD} lines: {len(h['over_hard'])}",
        "",
        "Every tracked file regardless of type. This set includes committed "
        "patches, binary blobs, generated JSON, and vendored dumps whose newline "
        "counts are not meaningful as module size — they are listed for "
        "completeness, not because the 500-line rule applies to them.",
        "",
        table(["path", "LOC", "binary", "area"],
              [[p, n, "yes" if files[p]["binary"] else "", top_dir(p)]
               for p, n in h["over_hard"]]),
        "",
        f"## All tracked files over {LIMIT_TARGET} lines: {len(h['over_target'])}",
        "",
        "Includes every file in the section above.",
        "",
        table(["path", "LOC", "over by", "binary", "area"],
              [[p, n, n - LIMIT_TARGET, "yes" if files[p]["binary"] else "", top_dir(p)]
               for p, n in h["over_target"]]),
        "",
        "## Empty tracked files (0 bytes, regular files)",
        "",
        table(["path"], [[p] for p in sorted(p for p in paths
                                             if files[p]["kind"] == "reg"
                                             and files[p]["size"] == 0)]),
        "",
    ])
    return "\n".join(out)
